// Code generated by goctl. DO NOT EDIT.
package types

type PingInfoResponse struct {
	Text string `json:"text"`
}

type TestInfoResponse struct {
	Text string `json:"text"`
}

type PickupInfoRequest struct {
	Imagescode string `json:"imagescode"`
}

type PickupInfoResponse struct {
	Id         int    `json:"id"`
	PickupCode string `json:"pickupCode"`
	PickupName string `json:"pickupName"`
	Status     int    `json:"status"`
	CreateTime string `json:"createTime"`
}
