// Code generated by sql2gorm. DO NOT EDIT.
package model

// 用户取件表
type PickupInfo struct {
	ID         int    `gorm:"column:id;type:int(10);primary_key;AUTO_INCREMENT" json:"id"`
	UserID     int    `gorm:"column:user_id;type:int(10);default:0;NOT NULL" json:"user_id"`             // 用户ID
	Name       string `gorm:"column:name;type:varchar(20);NOT NULL" json:"name"`                         // 用户名称
	Phone      string `gorm:"column:phone;type:varchar(20);NOT NULL" json:"phone"`                       // 手机号
	Text       string `gorm:"column:text;type:varchar(20);NOT NULL" json:"text"`                         // 取件文本
	NewText    string `gorm:"column:new_text;type:varchar(20);NOT NULL" json:"new_text"`                 // 新文本
	PickupCode string `gorm:"column:pickup_code;type:varchar(20);default:0;NOT NULL" json:"pickup_code"` // 取件码
	Status     int    `gorm:"column:status;type:int(10);default:0;NOT NULL" json:"status"`               // 是否取件，0-否，1-是
	CreateTime int    `gorm:"column:create_time;type:int(10);default:0;NOT NULL" json:"create_time"`     // 添加时间
	UpdateTime int    `gorm:"column:update_time;type:int(10);default:0;NOT NULL" json:"update_time"`     // 更新时间
}

func (m *PickupInfo) TableName() string {
	return "pickup_info"
}
